name: Test building simple packages from AUR

on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build package
      uses: ./
      with:
        packages: |
          go-do
